name: Docker Build & Azure Container Apps Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/apprep:latest
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        containerAppName: tpappreparti
        imageToDeploy: ${{ secrets.DOCKERHUB_USERNAME }}/apprep:latest
        targetPort: 8080
        environmentVariables: "SPRING_PROFILES_ACTIVE=prod"