name: Docker Build & Azure Container Apps Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/apprep:latest
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Container App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Create or update container app
          az containerapp update \
            --name tpappreparti \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/apprep:latest \
            --environment ${{ secrets.AZURE_CONTAINER_APP_ENVIRONMENT }} \
            --ingress external \
            --target-port 8080 \
            --env-vars "SPRING_PROFILES_ACTIVE=prod"